name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' # Empêche la publication sur pub.dev

version: 1.0.0+1

# Configuration du nom de l'application
launcher_name:
  default: "My Note"
  fr: "My Note"

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  launcher_name: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

# Configuration des icônes de l'application
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/note_icon_final_clean.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/note_icon_final_clean.png"

# Assets (décommenter si nécessaire)
# assets:
#   - assets/images/
#   - assets/icons/
